import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

const folioFont = localFont({
  src: [
    {
      path: '../public/fonts/folio-std-webfont/Folio-Std-Medium.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/folio-std-webfont/Folio-Std-Bold.woff',
      weight: '600',
      style: 'bold',
    },
    {
      path: '../public/fonts/folio-std-webfont/Folio-Std-Light.woff',
      weight: '300',
      style: 'light',
    },
  ],
  variable: '--font-folio',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${folioFont.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
